---
title: "Dashboard Base"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A


<iframe src="https://estadisticaun.github.io/G_Aspirantes/20181/Pre/Nac_col1.html" width="1200" height="860" style="border: 0" mozallowfullscreen="true" webkitallowfullscreen="true" allowfullscreen="true"><a href="https://estadisticaun.github.io/G_Aspirantes/20181/Pre/Nac_col1.html" target="_blank">OECD Chart: Real GDP forecast, Total, Annual growth rate (%), Annual, 2019</a></iframe>



Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

library(ggplot2)
ggplot(iris, aes(x = Sepal.Width, y = Petal.Length , col = Species)) + geom_point(size =5)

```

### Chart C



```{r}

library(leaflet)

m <- leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=174.768, lat=-36.852, popup="The birthplace of R")
m  # Print the map

```

